package com.neoterux.espfier.custom

import java.util.*
import kotlin.collections.ArrayList

/**
 * Contains the colors generated by an instance of the current app, are generated randomly.
 */
object ColorRepository {

    /**
     * Contains all the colors generated at runtime
     */
    val allColors = ArrayList<Color>().apply {
        while(size < 7){
            val gen = Color.random()
            if (!contains(gen))
                add(gen)
        }
    }

    /**
     * Get a Deque with all the colors generated at instance
     */
    fun copyColors() = ArrayDeque(allColors)
}
